version: '3.3'

services:

  db:
    image: mysql
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: allane
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8180:8080
