version: '2'

services:

  db:
    image: mysql:5.7.8
    restart: always
    ports:
    - 3306:3306
    environment:
      POSTGRES_DB: allene
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8180:8080
