version: '2'

services:

  db:
    image: postgres:11
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: payback
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8180:8080
